// Start of code segment generated by Google Gemini 3.1 Pro
import { system, world } from '@minecraft/server';

class dynamicProperty {
    constructor(source, name) {
        this.source = source;
        this.name = name;
    }
    get var() {
        return this.source.getDynamicProperty(this.name);
    }
    set var(value) {
        this.source.setDynamicProperty(this.name, value);
    }
}

world.afterEvents.playerSpawn.subscribe((eventData) => {
    const { initialSpawn, player } = eventData;
    if (initialSpawn) {
        let firstJoinToWorld = new dynamicProperty(world, "firstJoinToWorld");
        firstJoinToWorld.var ??= false;

        system.runTimeout(() => {
            if (!(player.hasTag("firstJoin"))) {
                player.addTag("firstJoin");
            }
            if (!firstJoinToWorld.var) {
                player.runCommand(`setblock 105814 218 105814 redstone_block`);
                firstJoinToWorld.var = true;
            }
        }, 1000);
    }
});

world.afterEvents.entitySpawn.subscribe((event) => {
    const { entity } = event;
    if (entity.typeId === "minecraft:item") {
        const item = entity.getComponent("minecraft:item").itemStack;
        if (item.typeId == "farlands:e_p_a_l_l") {
            entity.addTag("e_p_a_l_l");
        }
    }
});

// Optimization: Run every 10 ticks instead of every tick to save CPU
system.runInterval(() => {
    let players = world.getPlayers();
    for (const player of players) {
        
        // Optimization: Use direct property access instead of heavy array manipulation
        const loc = player.location;
        const blockLoc = {
            x: Math.floor(loc.x),
            y: Math.floor(loc.y) - 1, 
            z: Math.floor(loc.z)
        };

        let block = player.dimension.getBlock(blockLoc);
        
        if (block && block.typeId === "farlands:farlands_portal") {
            let tpOrigin = new dynamicProperty(player, "tpOrigin");

            tpOrigin.var = {
                x: Math.round(loc.x),
                y: Math.round(loc.y) + 2,
                z: Math.round(loc.z)
            };

            const farlandsPos = [
                [105476, 256, 105476],
                [105476, 256, -105476],
                [-105476, 256, 105476],
                [-105476, 256, -105476]
            ];
            
            // Generate a random index between 0 and 3
            const randomIndex = Math.floor(Math.random() * 4);
            const targetPos = farlandsPos[randomIndex];

            player.teleport({ x: targetPos[0], y: targetPos[1], z: targetPos[2] });
            player.runCommand(`effect @s slow_falling 60 1 true`);
        }
    }
}, 10);

world.afterEvents.itemUse.subscribe((eventData) => {
    const { itemStack, source } = eventData;
    if (source.typeId === "minecraft:player" && itemStack.typeId === "farlands:e_p_a_l_l") {
        let player = source;
        let tpOrigin = new dynamicProperty(player, "tpOrigin");
        if (tpOrigin.var !== undefined) {
            player.teleport(tpOrigin.var);
        }
        system.runTimeout(() => {
            player.runCommand(`clear @s farlands:e_p_a_l_l 0 1`);
            player.runCommand(`playsound mob.endermen.portal @s ~~~`);
            player.runCommand(`spreadplayers ~ ~ 3 5 @s`);
            player.runCommand(`effect @s slow_falling 60 1 true`);
        }, 3);
    }
});
// End of code segment generated by Google Gemini 3.1 Pro
